import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import { ModalProvider } from '@/providers/modal-provider';
import { ToasterProvider } from '@/providers/toast-provider';

import './globals.css';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });
const LazyThemeProvider = dynamic(() => import('@/providers/theme-provider'), { ssr: false })

export const metadata: Metadata = {
	title: 'Admin Dashboard',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<LazyThemeProvider attribute="class" defaultTheme="system" enableSystem >
						{children}
					</LazyThemeProvider	>
					<ModalProvider />
					<ToasterProvider />
				</body>
			</html>
		</ClerkProvider>
	);
}
